export const GLOBAL_CHANGE_DISPLAY_VIEW = 'GLOBAL_CHANGE_DISPLAY_VIEW';
export const GLOBAL_TOGGLE_SIDEBAR = 'GLOBAL_TOGGLE_SIDEBAR';
export const GLOBAL_TOGGLE_SIDEBAR_BUTTON_PRESS = 'GLOBAL_TOGGLE_SIDEBAR_BUTTON_PRESS';

export const AUTH_SIGNUP_REQUEST = 'AUTH_SIGNUP_REQUEST';
export const AUTH_SIGNUP_SUCCESS = 'AUTH_SIGNUP_SUCCESS';
export const AUTH_SIGNUP_FAILURE = 'AUTH_SIGNUP_FAILURE';

export const AUTH_LOGIN_REQUEST = 'AUTH_LOGIN_REQUEST';
export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS';
export const AUTH_LOGIN_FAILURE = 'AUTH_LOGIN_FAILURE';

export const AUTH_LOGOUT_REQUEST = 'AUTH_LOGOUT_REQUEST';
export const AUTH_LOGOUT_SUCCESS = 'AUTH_LOGOUT_SUCCESS';
export const AUTH_LOGOUT_FAILURE = 'AUTH_LOGOUT_FAILURE';

export const AUTH_REFRESH_TOKENS_REQUEST = 'AUTH_REFRESH_TOKENS_REQUEST';
export const AUTH_REFRESH_TOKENS_SUCCESS = 'AUTH_REFRESH_TOKENS_SUCCESS';
export const AUTH_REFRESH_TOKENS_FAILURE = 'AUTH_REFRESH_TOKENS_FAILURE';

export const ADMIN_FETCH_DATA_REQUEST = 'ADMIN_FETCH_DATA_REQUEST';
export const ADMIN_FETCH_DATA_SUCCESS = 'ADMIN_FETCH_DATA_SUCCESS';
export const ADMIN_FETCH_DATA_FAILURE = 'ADMIN_FETCH_DATA_FAILURE';

export const ADMIN_CREATE_DATA_REQUEST = 'ADMIN_CREATE_DATA_REQUEST';
export const ADMIN_CREATE_DATA_SUCCESS = 'ADMIN_CREATE_DATA_SUCCESS';
export const ADMIN_CREATE_DATA_FAILURE = 'ADMIN_CREATE_DATA_FAILURE';

export const ADMIN_UPDATE_DATA_REQUEST = 'ADMIN_UPDATE_DATA_REQUEST';
export const ADMIN_UPDATE_DATA_SUCCESS = 'ADMIN_UPDATE_DATA_SUCCESS';
export const ADMIN_UPDATE_DATA_FAILURE = 'ADMIN_UPDATE_DATA_FAILURE';

export const ADMIN_DELETE_DATA_REQUEST = 'ADMIN_DELETE_DATA_REQUEST';
export const ADMIN_DELETE_DATA_SUCCESS = 'ADMIN_DELETE_DATA_SUCCESS';
export const ADMIN_DELETE_DATA_FAILURE = 'ADMIN_DELETE_DATA_FAILURE';

export const ADMIN_CHANGE_FORM_FIELD_VALUE = 'ADMIN_CHANGE_FORM_FIELD_VALUE';
export const ADMIN_RESET_FORM_FIELDS = 'ADMIN_RESET_FORM_FIELDS';

export const ADMIN_CHANGE_CURRENT_MODEL = 'ADMIN_CHANGE_CURRENT_MODEL';
export const ADMIN_SET_RELOAD_DATA_TRIGGER = 'ADMIN_SET_RELOAD_DATA_TRIGGER';
export const ADMIN_TOGGLE_ITEM_SELECT = 'ADMIN_TOGGLE_ITEM_SELECT';
export const ADMIN_TOGGLE_ALL_ITEMS_SELECT = 'ADMIN_TOGGLE_ALL_ITEMS_SELECT';
export const ADMIN_SET_CURRENT_PAGE = 'ADMIN_SET_CURRENT_PAGE';
export const ADMIN_SET_ITEMS_PER_PAGE = 'ADMIN_SET_ITEMS_PER_PAGE';
export const ADMIN_SET_TOTAL_ITEMS = 'ADMIN_SET_TOTAL_ITEMS';
export const ADMIN_SET_LIST_DATA = 'ADMIN_SET_LIST_DATA';
export const ADMIN_SET_LIST_ITEMS_IDS = 'ADMIN_SET_LIST_ITEMS_IDS';
export const ADMIN_SEARCH_DATA_INIT = 'ADMIN_SEARCH_DATA_INIT';
export const ADMIN_SEARCH_DATA_COMPLETE = 'ADMIN_SEARCH_DATA_COMPLETE';
export const ADMIN_CHANGE_SEARCH_VALUE = 'ADMIN_CHANGE_SEARCH_VALUE';
export const ADMIN_CHANGE_SORT_STATE = 'ADMIN_CHANGE_SORT_STATE';
export const ADMIN_ADD_FILTER = 'ADMIN_ADD_FILTER';
export const ADMIN_DELETE_FILTER = 'ADMIN_DELETE_FILTER';
export const ADMIN_SET_FILTER_OPTIONS = 'ADMIN_SET_FILTER_OPTIONS';
export const ADMIN_SET_FILTER_TARGET = 'ADMIN_SET_FILTER_TARGET';
export const ADMIN_SET_CUSTOM_FIELDS = 'ADMIN_SET_CUSTOM_FIELDS';

export const CLIENT_FETCH_FREE_AGENTS_REQUEST = 'CLIENT_FETCH_FREE_AGENTS_REQUEST';
export const CLIENT_FETCH_FREE_AGENTS_SUCCESS = 'CLIENT_FETCH_FREE_AGENTS_SUCCESS';
export const CLIENT_FETCH_FREE_AGENTS_FAILURE = 'CLIENT_FETCH_FREE_AGENTS_FAILURE';

export const CLIENT_CREATE_RESERVATION_REQUEST = 'CLIENT_CREATE_RESERVATION_REQUEST';
export const CLIENT_CREATE_RESERVATION_SUCCESS = 'CLIENT_CREATE_RESERVATION_SUCCESS';
export const CLIENT_CREATE_RESERVATION_FAILURE = 'CLIENT_CREATE_RESERVATION_FAILURE';

export const CLIENT_CONFIRM_RESERVATION_REQUEST = 'CLIENT_CONFIRM_RESERVATION_REQUEST';
export const CLIENT_CONFIRM_RESERVATION_SUCCESS = 'CLIENT_CONFIRM_RESERVATION_SUCCESS';
export const CLIENT_CONFIRM_RESERVATION_FAILURE = 'CLIENT_CONFIRM_RESERVATION_FAILURE';

export const CLIENT_RESET_RESERVING_RESULTS = 'CLIENT_RESET_RESERVING_RESULTS';

export const CLIENT_SEND_EMAIL_REQUEST = 'CLIENT_SEND_EMAIL_REQUEST';
export const CLIENT_SEND_EMAIL_SUCCESS = 'CLIENT_SEND_EMAIL_SUCCESS';
export const CLIENT_SEND_EMAIL_FAILURE = 'CLIENT_SEND_EMAIL_FAILURE';

export const CLIENT_CHANGE_FORM_FIELD_VALUE = 'CLIENT_CHANGE_FORM_FIELD_VALUE';
export const CLIENT_CHANGE_FORM_FIELD_CONFIG = 'CLIENT_CHANGE_FORM_FIELD_CONFIG';
export const CLIENT_RESET_FORM_FIELDS = 'CLIENT_RESET_FORM_FIELDS';
export const CLIENT_SET_RELOAD_DATA_TRIGGER = 'CLIENT_SET_RELOAD_DATA_TRIGGER';
export const CLIENT_SHOW_START_FORM = 'CLIENT_SHOW_START_FORM';
export const CLIENT_HIDE_START_FORM = 'CLIENT_HIDE_START_FORM';
export const CLIENT_SET_CURRENT_PAGE = 'CLIENT_SET_CURRENT_PAGE';
export const CLIENT_SET_ITEMS_PER_PAGE = 'CLIENT_SET_ITEMS_PER_PAGE';
export const CLIENT_SET_TOTAL_ITEMS = 'CLIENT_SET_TOTAL_ITEMS';
export const CLIENT_SET_LIST_DATA = 'CLIENT_SET_LIST_DATA';
export const CLIENT_SET_LIST_ITEMS_IDS = 'CLIENT_SET_LIST_ITEMS_IDS';
export const CLIENT_CHANGE_SORT_TARGET = 'CLIENT_CHANGE_SORT_TARGET';
export const CLIENT_CHANGE_SORT_ORDER = 'CLIENT_CHANGE_SORT_ORDER';
export const CLIENT_CHANGE_FILTER_TARGET = 'CLIENT_CHANGE_FILTER_TARGET';
export const CLIENT_TOGGLE_ACTIVE_FORM = 'CLIENT_TOGGLE_ACTIVE_FORM';