export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';

export const REFRESH_TOKENS_REQUEST = 'REFRESH_TOKENS_REQUEST';
export const REFRESH_TOKENS_SUCCESS = 'REFRESH_TOKENS_SUCCESS';
export const REFRESH_TOKENS_FAILURE = 'REFRESH_TOKENS_FAILURE';

export const FETCH_DATA_REQUEST = 'FETCH_DATA_REQUEST';
export const FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS';
export const FETCH_DATA_FAILURE = 'FETCH_DATA_FAILURE';

export const CREATE_DATA_REQUEST = 'CREATE_DATA_REQUEST';
export const CREATE_DATA_SUCCESS = 'CREATE_DATA_SUCCESS';
export const CREATE_DATA_FAILURE = 'CREATE_DATA_FAILURE';

export const UPDATE_DATA_REQUEST = 'UPDATE_DATA_REQUEST';
export const UPDATE_DATA_SUCCESS = 'UPDATE_DATA_SUCCESS';
export const UPDATE_DATA_FAILURE = 'UPDATE_DATA_FAILURE';

export const DELETE_DATA_REQUEST = 'DELETE_DATA_REQUEST';
export const DELETE_DATA_SUCCESS = 'DELETE_DATA_SUCCESS';
export const DELETE_DATA_FAILURE = 'DELETE_DATA_FAILURE';

export const FETCH_FREE_AGENTS_REQUEST = 'FETCH_FREE_AGENTS_REQUEST';
export const FETCH_FREE_AGENTS_SUCCESS = 'FETCH_FREE_AGENTS_SUCCESS';
export const FETCH_FREE_AGENTS_FAILURE = 'FETCH_FREE_AGENTS_FAILURE';

export const CREATE_ORDER_REQUEST = 'CREATE_ORDER_REQUEST';
export const CREATE_ORDER_SUCCESS = 'CREATE_ORDER_SUCCESS';
export const CREATE_ORDER_FAILURE = 'CREATE_ORDER_FAILURE';

export const CHANGE_INPUT_FORM_STATE = 'CHANGE_INPUT_FORM_STATE';
export const REFRESH_INPUT_FORM_STATE = 'REFRESH_INPUT_FORM_STATE';

export const CHANGE_DISPLAY_VIEW = 'CHANGE_DISPLAY_VIEW';
export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR';
export const TOGGLE_SIDEBAR_BUTTON_PRESS = 'TOGGLE_SIDEBAR_BUTTON_PRESS';

export const CHANGE_CURRENT_MODEL = 'CHANGE_CURRENT_MODEL';
export const SET_RELOAD_DATA_TRIGGER = 'SET_RELOAD_DATA_TRIGGER';
export const TOGGLE_LIST_ITEM_SELECT = 'TOGGLE_LIST_ITEM_SELECT';
export const SET_SELECT_ALL_TRIGGER = 'SET_SELECT_ALL_TRIGGER';
export const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE';
export const SET_ITEMS_PER_PAGE = 'SET_ITEMS_PER_PAGE';
export const SET_TOTAL_ITEMS = 'SET_TOTAL_ITEMS';